# Generated by Django 2.1.2 on 2018-11-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('dia', models.DateTimeField()),
            ],
        ),
    ]
