# Generated by Django 2.1.2 on 2018-10-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='imgBD/'),
        ),
    ]
