# Generated by Django 2.1.2 on 2018-11-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0002_avaliacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.AddField(
            model_name='dados_musculos',
            name='doc_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dados_musculos',
            name='dia',
            field=models.DateField(),
        ),
    ]
