# Generated by Django 2.1.2 on 2018-10-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0003_auto_20181026_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
