# Generated by Django 2.1.2 on 2018-11-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0003_delete_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_musculos',
            name='dia',
            field=models.DateField(),
        ),
    ]
