# Generated by Django 2.1.2 on 2018-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0004_remove_dados_musculos_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_musculos',
            name='dadosMusculos',
            field=models.IntegerField(),
        ),
    ]
