# Generated by Django 2.1.2 on 2018-10-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0005_auto_20181027_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='paciente_fotos'),
        ),
    ]
