# Generated by Django 2.1.2 on 2018-11-01 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0006_auto_20181029_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao_paciente',
            name='paciente',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='kaorawebpages.Paciente'),
            preserve_default=False,
        ),
    ]
