# Generated by Django 2.1.2 on 2018-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0006_auto_20181029_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_musculos',
            name='parteAnalisada',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
