# Generated by Django 2.1.2 on 2018-11-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0007_dados_musculos_parteanalisada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_musculos',
            name='parteAnalisada',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
