# Generated by Django 2.1.2 on 2018-11-03 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0008_auto_20181102_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados_musculos',
            name='parteAnalisada',
        ),
    ]
