# Generated by Django 2.1.2 on 2018-11-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0009_remove_dados_musculos_parteanalisada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_musculos',
            old_name='dados_musculos',
            new_name='dadosMusculos',
        ),
    ]
