# Generated by Django 2.1.2 on 2018-11-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaorawebpages', '0010_auto_20181103_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_musculos',
            old_name='data',
            new_name='dia',
        ),
    ]
